import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Commons Upgrade</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          The Token Engineering Commons Enters the Next Phase
        </h1>

        <p className={styles.description}>
        We as a community, as a Commons, have accomplished every milestone along our path with a holistic and inclusive process. 
        </p>

        <div className={styles.rectangle2}></div>
        <div className={styles.rectangle3}></div>
        <div className={styles.circle1}></div>
        <div className={styles.circle2}></div>
        <div className={styles.circlegray}></div>

        <p className={styles.introhatch}>The Hatch</p>
        <p className={styles.introwerehere}>We are here!</p>
        <p className={styles.introcommonsupgrade}>Commons Upgrade</p>
        <p className={styles.introlaunch}>Launch</p>
        
        <div className={styles.grid}>
          <h2 className={styles.button}>
            <Link href="intro-2">
                <a>What's next?</a>
            </Link>
          </h2>
        </div>
        

      </main>
    </div>
  )
}
