import Link from 'next/link'
import Head from 'next/head'

import styles from '../../styles/Home.module.css'

export default function Intro2() {
    return (
      <div className={styles.container}>
        <Head>
          <title>Commons Upgrade</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>
            Your economy, your choice
          </h1>

          <div className={styles.grid}>
            <div>
              <h2 className={styles.button}>
                <Link href="/">
                    <a>Back</a>
                </Link>
              </h2>
            </div>
            
            <div>
              <h2 className={styles.button}>
                <Link href="intro-3">
                    <a>Next</a>
                </Link>
              </h2>
            </div>
          </div>
        </main>
      </div>
  )
  }